cobalt-org/cobalt.rs

.gitignore
.travis.yml
Cargo.lock
Cargo.toml
README.md
example/_layouts/default.tpl
example/_layouts/posts.tpl
src/cobalt.rs
src/document.rs
src/lib.rs
src/main.rs
src/util.rs

Basically the whole thing rewritten, since unfortunately for us Rust's io module got completely overhauled.
Cobalt now uses our very own liquid template engine, which is still very unstable but will do its job of filling in attributes in templates just fine. Working on adding more tags like a proper ``for`` loop.
Still much TODO, ideas are at the bottom of the readme for now.

Fixes for nightly, switch to liquid

---

README.md

cobalt builts quite fine with Rust 1.3.0, the documentation seems outdated.

Drop nightly requirement in README

---

src/cobalt.rs
src/document.rs

`unwrap()` produces panics with no explanation, and on some platforms there are no line numbers in the backtrace even in debug builds (rust-lang/rust#24346). `expect()` with an informative message is a much better user experience.
before:
$ ag -Q 'unwrap(' src | wc -l
15
after:
$ ag -Q 'unwrap(' src | wc -l
0
I made my best guess for an explanation at each error location, but they should be audited by someone who knows how the code works!

replace unwrap() with expect(format!(...))

---

tests/fixtures/example/index.tpl
tests/target/example/index.html

Commits:
* in ```tests/target/examples.html``` change test data to require each post title to be wrapped in a ```<a>``` tag linking to the post.
* in ```tests/fixtures/example/index.tpl```, in the code's map loop over posts, wrap each post title outputted in an ```<a>``` tag that makes use of the special ```{{post.name}}``` attribute in the value for its href attribute.
Reason:
* tests that post.name attribute works
* demonstrates to new users the usage of ```{{post.name}}``` for linking to posts in an index page.

Include test, example of special post.name attribute in tests

---

Cargo.toml
src/cobalt.rs
src/document.rs
src/error.rs
src/lib.rs
tests/fixtures/liquid_error/_layouts/default.tpl
tests/fixtures/liquid_error/_layouts/posts.tpl
tests/fixtures/liquid_error/_posts/2014-08-24-my-first-blogpost.md
tests/fixtures/liquid_error/index.tpl
tests/fixtures/no_extends_error/_layouts/default.tpl
tests/fixtures/no_extends_error/_layouts/posts.tpl
tests/fixtures/no_extends_error/_posts/2014-08-24-my-first-blogpost.md
tests/fixtures/no_extends_error/index.tpl
tests/mod.rs

- Uses liquid 0.2, which does better error handling
- Introduces a cobalt::Error that converts from the different error
types and enables much conciser and safer code
- Transitions all panics and unwraps to use the new error system

Better error handling (fixes #34)

---

Cargo.toml
src/cobalt.rs
src/document.rs
src/lib.rs
src/main.rs

This commit implements logging using the log and env_logger crates. The
lib part of cobalt strictly relies on using only log! macros to be
friendly to usage by other consumers.
main.rs uses env_logger to set different logging levels based on command
line flags, not environment variables.
The default log level is info. Optional log levels are debug and trace.
Logging can be turned of completely by passing --silent.
Feel free to litter the code with trace! and occasional debug! calls.

Implement better logging (closes #39)

---

Cargo.toml
src/document.rs
src/lib.rs
tests/target/custom_template_extensions/_posts/2014-08-24-my-first-blogpost.html
tests/target/dotfiles/_posts/2014-08-24-my-first-blogpost.html
tests/target/example/_posts/2014-08-24-my-first-blogpost.html
tests/target/rss/_posts/my-fifth-blogpost.html
tests/target/rss/_posts/my-first-blogpost.html
tests/target/rss/_posts/my-fourth-blogpost.html
tests/target/rss/_posts/my-second-blogpost.html
tests/target/rss/_posts/my-third-blogpost.html
tests/target/sort_posts/_posts/my-first-blogpost.html
tests/target/sort_posts/_posts/my-fourth-blogpost.html
tests/target/sort_posts/_posts/my-second-blogpost.html
tests/target/sort_posts/_posts/my-third-blogpost.html

This commit removes the dependency on markdown.rs for now, as
pulldown_cmark offers more compatibility and stability. However,
depending on how the two libraries turn out, we might want to consider
switching back again. None of the alternatives for Rust markdown parsing
is in a great state, currently.

Switch to pulldown-cmark for markdown parsing

---

Cargo.toml
src/config.rs
src/main.rs

Adds watch command and other things:
TODO:
Let me know if there is anything else that should be added/changed.

Add Watch command

---

src/cobalt.rs

No idea when they got lost, but cloning both Vecs for each iteration
obviously isn't a good idea.

Wrap shared Vecs in Arc during document creation

---

Cargo.toml
src/main.rs

Last week I wrote a small gh-pages import library similar to ghp-import that was written in python. I have added a subcommand for `cobalt`. Let me know what you think @johannhof . I was also thinking it may be better to have it `cobalt build --upload` rather than `cobalt upload`.

added upload command with ghp-rs

---

.travis.yml

This should allow coverage to only be done on stable. To my understanding this should fix it.

kcov travis fix

---

Cargo.toml
src/cobalt.rs
src/config.rs
src/lib.rs
tests/fixtures/ignore_files/.cobalt.yml
tests/fixtures/ignore_files/README
tests/fixtures/ignore_files/_layouts/default.liquid
tests/fixtures/ignore_files/_layouts/posts.liquid
tests/fixtures/ignore_files/_posts/2014-08-24-my-first-blogpost.md
tests/fixtures/ignore_files/index.liquid
tests/fixtures/ignore_files/some.js
tests/fixtures/ignore_files/style/blog.css
tests/fixtures/ignore_files/style/blog.scss
tests/mod.rs
tests/target/ignore_files/_posts/2014-08-24-my-first-blogpost.html
tests/target/ignore_files/index.html
tests/target/ignore_files/some.js
tests/target/ignore_files/style/blog.css

I have added an extra config parameter to ignore files in the files walker
(this helps to exclude files to not publish things accidentally). This can help
to fix the watch infinite loop adding to ignore config the "*.html" glob (#84).
In the future I can add --ignore parameter or --ignore-file parameter to add
ignore patterns in the current run.

Add ignore config

---

src/main.rs

This should fix the watch command recursively calling itself on mac. We will have to check with the notify crate to check how the other file notifiers notify what file is changed. This is a fix for #84.

Fix for watch command recursive call

---

src/document.rs

The PR contains one feature and one fix. I can split it up into two PRs if you like, but I feel like the fix is too small for a separate PR.
The feature is a new `date` filter so that one can do `post.date | date:"%d/%m/%y"` in liquid templates (example usage: https://github.com/kstep/kstep.github.com/blob/master/src/index.liquid#L17). Although it seems like liquid parser contains another bug: it doesn't parse filter arguments correctly, so I can't use spaces in the `date` filter arguments (I worked it around by using `&nbsp;` entity instead).
The fix is the incorrect YAML header splitting from markdown files. It splits files by all instances of `---` separator, while it should use the first one only. The fix is pretty obvious and self-explanatory.
---
This change is [<img …

Liquid date filter

---

Cargo.toml
src/cobalt.rs
tests/cli.rs

This adds a CLI testing mechanism around [assert_cli](https://github.com/killercup/assert_cli) that we should use to add more CLI tests.

Add basic CLI tests

---

src/main.rs

All the PRs to master are currently red due to style issues:
```
$ cargo fmt -- --write-mode=diff &&
travis-cargo build &&
travis-cargo test
Diff in /home/travis/build/cobalt-org/cobalt.rs/src/main.rs at line 294:
let rel_path = path.strip_prefix(&cwd).unwrap_or(&cwd);⏎
⏎
// check if path starts with the build folder.⏎
-                                        if !&config.ignore.iter().any(|pattern| {⏎
-                                            Pattern::matches_path(pattern, rel_path)⏎
-                                        }) {⏎
+                                        if ⏎
+                                               !&config.ignore⏎
+                                            .iter()⏎
+                                            .any(|pattern| Pattern::matches_path(pattern, …
```

Fix style issue reported by cargo fmt

---

README.md

[GitLab Pages](http://pages.gitlab.io/) are now deployed using GitLab CI.
I've removed notes about `gl-pages` and added an example of `.gitlab-ci.yml`.
This has been tested on my blog and seems to be working.

Update GitLab Pages instructions in README.md

---

src/main.rs

There was a bug when `path` contained `./` as prefix (e.g. `./build/index.html`). Now `path::PathBuf` takes care of corner cases like this.
The bug described above meant there was an infinite rebuild loop in `cobalt watch` even when `build` directory was marked as ignored:
* on each rebuild some files in `build` directory were updated
* `inotify` started new rebuilds on these updates

watch should never rebuild on changes that are ignored

---

Cargo.toml
src/cobalt.rs
src/document.rs
src/lib.rs

In #138 and #145 I noticed that it might be beneficial to render posts
before documents, because documents might want to access post
information such as content or excerpt that requires all posts to be
rendered.
This also removes the admittedly naive approach of spawning a thread per
document which at least by my measurements adds way too much overhead to
be of any use. I will open a new issue for experimenting with ways to
add good parallelism.
Fixes #138 by adding a "content" attribute to posts.

Render posts before documents, remove threading

---

.gitignore
Cargo.lock

The best practice is to keep this file in gitignore for libraries and in repo for applications.
Committing Cargo.lock makes the builds much more reproducible.
Note: I've called `cargo update` just before creating this PR, so I hope all the dependencies are now up-to-date.

Add Cargo.lock to repository

---

src/cobalt.rs
src/document.rs
tests/target/rss/rss.xml

This PR:
- uses excerpt or content as a default value for description in rss
- adds guid tag to rss feed (as suggested by [validator.w3.org](https://validator.w3.org/feed/docs/warning/MissingGuid.html))

RSS: use content as a default description, add guid

---

src/cobalt.rs
src/main.rs
tests/cli.rs

fixes #102 
If there is a cleaner way to do this, please let me know.
I kept getting `expected (), found enum 'std::result::Result\'` but writing it this way worked.
I did not add a test for this just yet but trying to figure that out.

adding clean command

---

Cargo.lock
Cargo.toml
src/error.rs
src/lib.rs

I thought using [*error-chain*](https://crates.io/crates/error-chain) might be nice because it removes a lot of overhead code.
It also enables easy addition of errors. This in turn means that one can use more detailed `ErrorKind`s than a `String` *so* easy that people actually add verbose error handling.
Furthermore it makes it possible to use *error-chain* in projects that depend on *cobalt.rs* to "include" it's error chain directly.

error-chain for error handling

---

src/cobalt.rs
src/error.rs
tests/mod.rs

Depends on #156.
Replaces the error generated on incomplete RSS configs with an `ErrorKind` instead of a `String`.

ErrorKind error instead of String

---

.gitignore

Ignores vim's `.<filename>.swp` files.

gitignore for vim

---

Cargo.lock
Cargo.toml
README.md
src/document.rs
src/lib.rs
src/syntax_highlight.rs
tests/cli.rs
tests/fixtures/syntax_highlight/rust.md
tests/mod.rs
tests/target/syntax_highlight/rust.html

This work adds syntax highlighting to cobalt using the awesome syntect library. This still work in progress, not ready for merging yet!

Adding syntax highlighting

---

Cargo.lock
src/cobalt.rs
src/error.rs

While working on another PR I've noticed that nightly travis builds are broken due to an old version of clippy (0.0.98).
This PR bumps clippy to the recent available version and fixes or ignores found clippy violations.
Red job example: [jobs/189656668](https://travis-ci.org/cobalt-org/cobalt.rs/jobs/189656668)

Bump clippy to 0.0.106 to fix nightly (1.16) travis builds

---

src/new.rs

Fixes #169 (reported by @uetoyo)
How to test this PR manually:
* create new blog with `cobalt new`
* add non-ascii text in utf-8 to `posts/post-1.md`
* build the blog
* open post 1 in Firefox
I don't think we need to cover this with unit tests.

Set charset utf-8 in the default template

---

src/cobalt.rs

While calculating the relative path, trim away the starting `/`. Otherwise,
`dest.join` ends up ignoring `dest` altogether and tries to create the directory
under root (say `/posts`).
To reproduce, try (in OSX El Capitan):
```bash
$ cobalt new
[warn]   No .cobalt.yml file found in current directory, using default config.
[info]   Created new project at ./
```
.cobalt.yml
```yaml
name: cobalt blog
source: "."
dest: "build"
ignore:
- .git/*
- build/*
```
```bash
$ cobalt build
[info]   Using config file .cobalt.yml
[info]   Building from . into build
[info]   Created build/posts/post-1.html
[info]   Created build/index.html
[info]   Copying remaining assets
[error]  Permission denied (os error 13)
[error]  Build not successful
```
Used the following extracted out code to experiment:
```rust …
```

Trim starting `/` from relative entry path

---

.travis.yml
README.md
appveyor.yml
ci/before_deploy.ps1
ci/before_deploy.sh
ci/coverage.sh
ci/install.sh
ci/script.sh
src/cobalt.rs
src/document.rs
src/error.rs
src/lib.rs
src/main.rs
tests/cli.rs
tests/fixtures/custom_paths/posts/all_date_variables.md
tests/fixtures/custom_paths/posts/custom-leading-slash.md
tests/fixtures/custom_paths/posts/custom.md
tests/fixtures/custom_paths/posts/date_variables.md
tests/fixtures/custom_paths/posts/explodes-urls-without-trailing-slash.md
tests/fixtures/custom_paths/posts/explodes-urls.md
tests/fixtures/custom_paths/posts/no-path.md
tests/fixtures/custom_paths/posts/variables.md
tests/fixtures/custom_paths/posts/variables_file.md
tests/target/custom_paths/2015/05/5/03/3/01/05/20/index.html
tests/target/custom_paths/index.html

This switches our CI to a system that
The system is originally based on https://github.com/japaric/trust but I made some pretty big changes along the way, including throwing out cross for now. We can easily drop it in once we need support for more exotic compilation targets.
cc @nott @gnunicorn

Le Big CI Overhaul

---

ci/coverage.sh

Somehow (caching?) there are multiple test binaries when running
coverage, so I'm adding a `cargo clean` to remove them.
Makes the whole thing slower, unfortunately

Fix coverage reporting

---

.travis.yml
ci/coverage.sh

This very likely solves the coverage problem without cleaning and rebuilding. I also added a sudo:false because I don't think we were running on container infrastructure by default 😅

Don't cache files in target/debug (fixes #178)

---

Cargo.lock
Cargo.toml
ci/before_deploy.sh
ci/script.sh

The new version of syntect allows us to statically link libonig, so let's see what our CI thinks of that.

Enable syntax-highlighting by default

---

src/document.rs
tests/fixtures/excerpts/posts/post-10.md
tests/fixtures/excerpts/posts/post-11.md
tests/fixtures/excerpts/posts/post-12.liquid
tests/fixtures/excerpts/posts/post-6.liquid
tests/fixtures/excerpts/posts/post-7.liquid
tests/fixtures/excerpts/posts/post-8.md
tests/fixtures/excerpts/posts/post-9.md
tests/target/excerpts/index.html
tests/target/excerpts/posts/post-10.html
tests/target/excerpts/posts/post-11.html
tests/target/excerpts/posts/post-12.html
tests/target/excerpts/posts/post-6.html
tests/target/excerpts/posts/post-7.html
tests/target/excerpts/posts/post-8.html
tests/target/excerpts/posts/post-9.html

This should address issue #186: feedback requested, as I'm still learning Rust.
I used the [regex from Jekyll](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/excerpt.rb#L120) to match the reference-style links.
Also, instead of creating a new set of tests, I added the tests to the existing excerpts test set: let me know if that's the preferred method.

Ref style links in excerpts

---

Cargo.lock
src/cobalt.rs

This PR fixes #194 : use the system dependent path separator instead of hard `"/"`.
I've also updated Cargo.lock for 0.6.0, but in the separate commit.

Win path fix

---

Cargo.lock
Cargo.toml
src/document.rs
src/lib.rs

Add document attributes "title", "slug", and "ext" if needed based on the
input-file.
The primary motivation for this change is to allow a custom "path" while
retaining the original :slug. A more surgical approach was taken rather
than trying to achieve 100% Jekyll-compatibility though Jekyll does serve
as an inspiration for how these features work.
The "slug" attribute defaults to a lower-case slugified version of the
document's filename.  The primary use is for specifying a custom "path"
attribute that still includes the original file name (via :slug).
Jekyll compatibility:
- Precedence: Allows a user to override "slug" in their front matter.
- Template variable for path: The default slug attempts to be formatted
like Jekyll
Jekyll incompatibility:
- General: Jekyll excludes …

feat(attributes): Add input-file based attributes

---

Cargo.lock
Cargo.toml
src/cobalt.rs
src/document.rs
src/error.rs
src/main.rs
tests/mod.rs

Upgrade notes:
- notify: Debouncing was added but have not yet switched to it because of
the extra work to extract the relevant path
Dependencies that were held back:
- assert_cli: See killercup/assert_cli#30 and killercup/assert_cli#31
- rss: Seems they turned off XML escaping.  Didn't have time to research
this.

chore: Upgrade dependencies

---

src/document.rs
tests/fixtures/empty_frontmatter/_layouts/default.liquid
tests/fixtures/empty_frontmatter/_layouts/posts.liquid
tests/fixtures/empty_frontmatter/index.liquid
tests/fixtures/empty_frontmatter/posts/my-first-blogpost.md
tests/mod.rs
tests/target/empty_frontmatter/index.html
tests/target/empty_frontmatter/posts/my-first-blogpost.html

On trying to port my site over, I encoutered crashes due to invalid index access with files that have a front matter such as:
```
---
name: ...
---
```
This gets parsed as an empty front matter due to beginning with dashes, which lead to the index error.
I'm not sure if empty frontmatter = error is the right thing or if we just want to treat it without problems.

fix(frontmatter): Support empty frontmatters

---

README.md
src/cobalt.rs
src/config.rs
tests/fixtures/post_order/.cobalt.yml
tests/fixtures/post_order/_layouts/default.liquid
tests/fixtures/post_order/_layouts/posts.liquid
tests/fixtures/post_order/index.liquid
tests/fixtures/post_order/posts/my-first-blogpost.md
tests/fixtures/post_order/posts/my-fourth-blogpost.md
tests/fixtures/post_order/posts/my-second-blogpost.md
tests/fixtures/post_order/posts/my-third-blogpost.md
tests/mod.rs
tests/target/post_order/index.html
tests/target/post_order/posts/my-first-blogpost.html
tests/target/post_order/posts/my-fourth-blogpost.html
tests/target/post_order/posts/my-second-blogpost.html
tests/target/post_order/posts/my-third-blogpost.html

Fix for #160 - post order is controlled by setting `post_order` to `asc` or `desc` in `.cobalt.yml` (default desc).

Allow posts to be reverse sorted

---

src/main.rs
tests/fixtures/querystrings/_layouts/default.liquid
tests/fixtures/querystrings/_layouts/posts.liquid
tests/fixtures/querystrings/index.liquid
tests/fixtures/querystrings/posts/2014-08-24-my-first-blogpost.md
tests/mod.rs
tests/target/querystrings/index.html
tests/target/querystrings/posts/2014-08-24-my-first-blogpost.html

Fix for #207 - strips querystrings from urls when serving files locally

Ignore querystrings

---

README.md
src/main.rs

Groundwork for #208 - `cobalt new` is now `cobalt init`

Rename the 'new' command to 'init'

---

.travis.yml

It is unclear why the default build isn't running anymore.  `trust`
explicitly calls it out now as well.

fix(CI): Re-enable Stable builds on Linux

---

Cargo.lock
Cargo.toml

Spoke with @trishume, and projects disabling syntect's default features
may run into API-breaking changes with minor version releases.  Bind
crate to patch version to avoid further incidents.
Syntect v1.7 adds dump-load and dump-load-rs options.  Select dump-load
since it's in syntect's default feature list and suspected to be
compatible with v1.5.  Consider switching to dump-load-rs after
sufficient testing.
Install successfully tested via:
```
cd path/to/cobalt/fork
cargo install --path ./ cobalt-bin --feature=syntax-highlight
```
Fixes #252

fix: Bump syntect version to 1.7.0 and enable dump-load feature

---

src/cobalt.rs
src/datetime.rs
src/document.rs
src/frontmatter.rs
src/lib.rs
src/slug.rs
tests/mod.rs
tests/target/custom_paths/2015/05/5/03/3/01/05/20/index.html
tests/target/custom_paths/2015/hello/index.html
tests/target/custom_paths/index.html
tests/target/custom_paths/test/hello/index.html
tests/target/custom_paths/test/thing3/index.html
tests/target/custom_paths/test/thing4/index.html
tests/target/custom_post_path/index.html

While this makes the code less optimal and a little weird in places (but cleaner in others), this gets all of the plumbing in place for #257 where cobalt uses serde to load a very strict frontmatter.
The other benefit to this gradual approach is that the old attributes -> frontmatter conversion is being heavily tested before the break.  As part of the break, it will be pulled out into a migration tool.
Cheap features we got while at it:
- Support `:categories` in permalinks
- Support nested frontmatter yaml
Breaking changes
- page `path` attribute no longer has an auto-appended "index.html".  The placement on disk doesn't change though.
- `slug`, `excerpt_separator`, `ext`, and `extends` are no longer page attributes.  The assumption is that these weren't even really needed except for …

chore: Refactor in preparation for #257

---

src/cobalt.rs
src/config.rs
src/document.rs
src/frontmatter.rs
src/main.rs

Added `--dump=DocLinkObject` to dump the substitutions that are
available for creating page paths.
In addition, `--dump` can now go before or after the sub-command.
BREAKING CHANGE: `--dump=liquid` is now split into `--dump=DocObject`
and `--dump=DocTemplate`.

feat(debug): Link substitutions dump flag added

---

src/cobalt.rs
src/config.rs
src/document.rs
src/error.rs
src/lib.rs
src/main.rs
src/syntax_highlight.rs

These patches build on @mre's initial work.  Only the default themes included by syntect are allowed.
~~I reverted @mre's changes to `Config`, `Document`, and `CodeBlock` since we only need to set the theme name once, and the `SETUP` variable already distributes themes to the `initialize_codeblock` and `decorate_markdown` functions.~~
~~I might be able to avoid the reversion with closures, but this PR is my third attempt, and I'd rather get feedback before I spend more time on this.~~
I tested the PR via the following process on Linux:
```
cd /tmp
git clone git@github.com:boxofrox/cobalt.rs.git
cd cobalt.rs
git checkout config-theme
cargo install --force cobalt-bin --path ./ --features=syntax-highlight
cd <cobalt-blog-directory>
cat "syntax-highlight:\n  theme: base16-ocean.light" >> …
```

Allow configuring the theme for syntax highlighting

---

src/lib.rs
src/main.rs
src/syntax_highlight.rs

I wrote this patch when I was messing around with #259.  Figured I'd toss it on here in case it could be of use to someone.  I think I wrote this when I was curious what keyword was needed on a code block I wanted to highlight, so it does that well, at least.
Would have provided the list of what languages are included in #200 (spoiler: not vimscript).
Format of output for `cobalt --list-syntaxes` is:
```
SyntaxName [FileExtension, ...]
...
```
From what I gleaned from the *syntect* docs/code, one can use the `SyntaxName` or `FileExtension` as the language token on a code block.  e.g.
```rust
fn main() {}
```
```rs
fn main() {}
```
However, I doubt that works for the `SyntaxName` or `FileExtension` that contains spaces.  I am baffled how one highlights regular expressions for javascript …

Add list-syntaxes subcommand to list file types supported by syntect

---

src/cobalt.rs
src/document.rs
src/frontmatter.rs
src/legacy/mod.rs
src/legacy/wildwest.rs
src/lib.rs
src/syntax_highlight/null.rs

This is preparation for changing the global config format in full preparation for breaking compatibility and providing a migration tool.

refactor: Clean up separation of old format

---

Cargo.lock
Cargo.toml
src/cobalt.rs
src/config.rs
src/error.rs
src/lib.rs
src/syntax_highlight/syntect.rs
tests/fixtures/config/.cobalt.yml
tests/fixtures/syntax_highlight_theme/.cobalt.yml
tests/fixtures/syntax_highlight_theme/rust.md
tests/mod.rs
tests/target/syntax_highlight_theme/rust.html

- This simplifies the config loading code.
- This is yet another stepping stone towards a revamped config.
- This allows the removal of a direct dependency.
BREAKING CHANGE:
Unknown fields are mostly not allowed now (for some reason, incorrect
syntax-highlight fields are).  There isn't really a use case for unknown
fields but room for a lot of confusion (typos in fields leading to odd
behavior).
`syntax-highlight` has been renamed to `syntax_highlight`.  This is more
consistent with the rest of the file.

refactor: Load `.cobalt.yml` via serde

---

src/cobalt.rs
src/config.rs
tests/fixtures/post_order/.cobalt.yml

In theory, this makes the checking more strict.  In practice, serde
isn't erroring out for invalid enum values as I'd expect.
BREAKING CHANGE: `post_order` now takes `Asc` and `Desc` instead of
`asc` and `desc`.

refactor: Use enum to describe post_order

---

src/config.rs
src/legacy/wildwest.rs

The internal and public formats are now decoupled.  This is in prep for
evolving the format while allowing compatibility until we get a
migration tool written.

refactor: Decouple config format

---

src/bin/cobalt/main.rs
src/document.rs
src/lib.rs
src/syntax_highlight/null.rs
src/syntax_highlight/syntect.rs

Explicitly listing warnings as suggested in the [anti-patterns](https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md) document.
The problem with this approach is that it is prohibitive to list clippy
warnings.  What would work well is for their to be `warnings` and
`clippy` warning groups that are versioned.

fix(CI): Ensure CI is future compatible with new rusts

---

Cargo.lock
src/bin/cobalt/build.rs
src/bin/cobalt/error.rs
src/bin/cobalt/main.rs
src/bin/cobalt/new.rs
src/bin/cobalt/serve.rs
src/cobalt.rs
src/config.rs
src/document.rs
src/new.rs
tests/mod.rs

This is meant as a replacement for #162.  That PR added some error handling in a few places.  This nearly replaces `process::exist` with error chaining.
While at it, I added context to some errors, like what file failed in parsing the liquid template.
For testing, I ran every command to make sure they worked correctly.

Rely on Result rather than killing the process

---

.travis.yml
Cargo.lock
Cargo.toml
src/cobalt.rs
src/config.rs
src/legacy/wildwest.rs
src/lib.rs
tests/fixtures/sass/_sass/_importable.scss
tests/fixtures/sass/_sass/_nested.scss
tests/fixtures/sass/style/blog.css
tests/fixtures/sass/style/main.scss
tests/fixtures/sass/style/nest.scss
tests/fixtures/sass_custom_config/.cobalt.yml
tests/fixtures/sass_custom_config/_sass_includes/_importable.scss
tests/fixtures/sass_custom_config/_sass_includes/_nested.scss
tests/fixtures/sass_custom_config/style/blog.css
tests/fixtures/sass_custom_config/style/main.scss
tests/fixtures/sass_custom_config/style/nest.scss
tests/mod.rs
tests/target/sass/style/blog.css
tests/target/sass/style/main.css
tests/target/sass/style/nest.css
tests/target/sass_custom_config/style/blog.css
tests/target/sass_custom_config/style/main.css
tests/target/sass_custom_config/style/nest.css

This is an attempt to implement supporting of compiling SASS/SCSS files, too.
It's using the nice sass-rs (which in turn uses sass-sys, to bind to libsass)
in order to compile statics files with the extension 'scss' into css files.
Progress / todo:
Comments, Review, Feedback and help welcome!
fixes #99

Add SCSS support

---

src/bin/cobalt/build.rs
src/bin/cobalt/serve.rs
src/cobalt.rs
src/config.rs
src/document.rs
src/files.rs
src/legacy/wildwest.rs
src/lib.rs
src/new.rs
src/site.rs
tests/mod.rs

The focus was on ground work for #199.
As part of this
- cobalt now exposes the following liquid variabes
- `site.name`
- `site.description`
- `site.base_url`
- Can be used to make correct paths, for example `{{site.base_url}}/{{post.path}}`.
- Fixes #171, #216 
- `watch` will now respect the `ignore` field
- Helps in people implementing workarounds
- Shouldn't break anything because ignored content shouldn't be used by cobalt anyways (unless someone ignores a normally-hidden-except-for-watch directory like `_data`)
- Fix ignoring `dest` in both `build` and `watch`
- Broken in #308.  It was adding an absolute path to be ignored rather than a relative
- Also ensured we didn't ignore non-dest directories that look like them
- Also hardened our detection of dest being a child of source
- …

Massively change configuration

---

src/site.rs

When we encounter an error reading a data-file (through serde not being willing to read it) or when merging it into the existing data set, it now names the file that is causing the error in the error message.

Provide Information when serde parsing fails

---

src/cobalt.rs
src/config.rs
src/legacy/wildwest.rs
src/site.rs

This is consistency with page.title.
(This also slips in a fix for jsonfeed to use the blog
title/description)
See #313

fix(site): Rename name to title

---

Cargo.lock
Cargo.toml
src/cobalt.rs
src/config.rs
src/document.rs
src/frontmatter.rs
src/legacy/wildwest.rs
tests/fixtures/copy_files/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/custom_paths/no-post.md
tests/fixtures/custom_posts_folder/blog/2014-08-24-my-first-blogpost.md
tests/fixtures/custom_template_extensions/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/dotfiles/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/drafts/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/drafts_not_shown_by_default/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/example/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/hidden_posts_folder/_blog/2014-08-24-my-first-blogpost.md
tests/fixtures/ignore_files/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/liquid_error/_posts/2014-08-24-my-first-blogpost.md
tests/fixtures/no_extends_error/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/previous_next/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/previous_next/posts/2014-08-25-my-second-blogpost.md
tests/fixtures/previous_next/posts/2014-08-26-my-third-blogpost.md
tests/fixtures/yaml_error/_posts/2014-08-24-my-first-blogpost.md
tests/target/previous_next/index.html
tests/target/previous_next/posts/2014-08-24-my-first-blogpost.html
tests/target/previous_next/posts/2014-08-25-my-second-blogpost.html
tests/target/previous_next/posts/2014-08-26-my-third-blogpost.html

Changes made because they were minor
- Infer `published_date` from filename (`YYYY-MM-DD Title`)
Changes made because they are currently hidden from the user
- Rename `path` to `permalink`
- `path` permalink alias
- permalinks will need to be absolute paths to distinguish from a permalink alias
- (not finished) collection (like posts) slug in permalinks
- Sass configuration will be under an `assets` section in prep for #318 and #322 
- `destination` will be `./_site`
Otherwise, TODOs were inserted

Update configuration in prep for major breaking changes

---

src/bin/cobalt/args.rs
src/bin/cobalt/main.rs
src/bin/cobalt/new.rs
src/cobalt.rs
src/config.rs
src/datetime.rs
src/document.rs
src/files.rs
src/jekyll/jk_document.rs
src/legacy/wildwest.rs
src/lib.rs
src/new.rs
src/sass.rs

`cobalt new` has improved semantics
- title is accepted (needs quotes for multi-word)
- filename is assumed to be the title's slug unless otherwise specified
- destination is assumed to be cwd unless otherwise specified
- page vs post is inferred from the destination
`cobalt publish` has been introduced
- Removes `draft` flag
- Sets `date` to now
To simplify this process
- `cobalt init` only generates `.md` files.
- new posts (`init` or `new`) start as drafts
Additionally, `cobalt init` has been made to align with more recently recommend practices.

Improve post-writing workflow

---

.travis.yml

I think its because we are using an old cargo-travis that doesn't
understand new cargo features.
I had to disable the caching of cargo-travis to upgrade it because we
have no way to make the cache auto-invalidate.  We'll just have to wait
until we can assume its propogate to all travis caches.

fix(CI): Try to fix coverage reporting

---

README.md

After experiencing problems with the old documented way of manually doing the import and push I simply switched over to Travis' native method and it works without a hassle.

Travis deploy integration

---

src/cobalt.rs
src/cobalt_model/frontmatter.rs
src/document.rs
src/legacy_model/frontmatter.rs

Original sequence of behavior
- front.excerpt was put in the page's attributes
- capture attributes
- render_excerpt renders using captured attribtes
- render_excerpt updates page's attributes
- render used the captured attributes which included the unredered
excerpt
The previous change made things worse
- capture attributes
- render_excerpt renders using captured attribtes
- render_excerpt updates page's attributes
- render used the captured attributes which had no excerpt
Now
- capture attributes
- render_excerpt renders using captured attribtes
- render_excerpt updates page's attributes
- capture attributes
- render used the updated captured attributes, including support for
excerpt

 fix(front): Ensure exceprt is rendered before used 

---

src/document.rs

This can be used for referencing assets in the folder the file came
from.
Fixes #338

feat(page): page.file.parent variable

---

src/bin/cobalt/serve.rs
src/cobalt.rs
src/cobalt_model/config.rs
src/cobalt_model/files.rs
src/cobalt_model/site.rs

This mostly resolves #356.  vim will cause a `delete` and `create`
notification on save.  The problem is that debouncing is really a
per-application policy rather than something that is universal.  It'd be
ideal for these to be debounced for cobalt but that wouldn't work in
other cases.

perf(serve): Reduce duplicate rebuilds

---

src/bin/cobalt/debug.rs
src/bin/cobalt/main.rs
src/cobalt.rs
src/cobalt_model/assets.rs
src/cobalt_model/config.rs
src/cobalt_model/files.rs
src/cobalt_model/mod.rs
src/legacy_model/config.rs

Refactor assets as a pattern for collection refactorings

---

src/cobalt.rs

I've split cobalt.rs build() function to make it easier to read

Split build() for readability

---

Cargo.lock
Cargo.toml
src/cobalt_model/collection.rs
src/cobalt_model/site.rs
src/document.rs
src/jekyll_model/frontmatter.rs
src/legacy_model/frontmatter.rs
src/template.rs
tests/mod.rs

Features
* Provide context on errors (good enough for #136)
* Implement basic `compact` support
Bug Fixes
* `date_in_tz` can't parse cobalt's dates
* Improve value coercion practices
* Every `Value` is now treated as a string.
* Whole numbers are now preserved.
* Whole numbers can convert to fractional numbers but not the other way
around.
* You can convert a fractional number to a whole number using the
filters `round`, `ceil`, or `floor`.
* Operations on only whole numbers preserve their whole number nature.
* for tag ranges, indexing, etc only accept whole numbers
Fixes #136
BREAKING CHANGES: There might be minor behavior changes form the coercion
changes.

 feat: Upgrade liquid 

---

src/cobalt.rs
src/document.rs
tests/mod.rs

Here is the follow up of https://github.com/cobalt-org/cobalt.rs/pull/369 applying your comments!

Rename some refactored fct

---

src/bin/cobalt/serve.rs

As the title, this is useful when you are testing/coding your site somewhere else maybe on ssh.
Regard

add option to bind the serve to a different host

---

src/bin/cobalt/build.rs
tests/cli.rs

Recently, when I used `import`, I made several mistakes.  This was in
part out of assumptions of how I thought it worked.  This changes import
to work like how I at least expect.
Import does:
- `cobalt clean`
- `cobalt build`
- and imports `destination` into the specified branch
Because of this extra processing, `cobalt build -i` has been removed.
Fixes #394.
BREAKING CHANGE: `cobalt build -i` no longer works.  Instead use `cobalt
import`.

 fix(import): import is self-contained

---

src/document.rs

This was removed in #257 because it was deemed as not being needed but a
use case was found in #384.  I'm not fully convinced about that use case
but I feel there are probably others, like in having an identifier to
use in creating a table of contents.
Fixed #384

feat(liquid): Add page.slug

---

src/bin/cobalt/main.rs
src/bin/cobalt/new.rs

`cobalt new` looks for a file that matches `_defaults/<collection>.<ext>` where:
- `collection` is the name of the collection (like `pages` or `posts`)
- `ext` is
- from `--with-ext`
- from `--file`
- otherwise `md`
If the file is not found, a built in is used.
I dislike the name `_defaults` but couldn't come up with a better.  The
only alternative I had was `_new`.
`cobalt init` will also now create the `_defaults` folder to help guide
users to this new feature.
Fixes #355

 feat(new): Load default files from disk 

---

src/bin/cobalt/main.rs
src/bin/cobalt/new.rs

Cobalt now has supprot for:
`cobalt rename <src_path> <new_title> [--file <dest_path>]`
This will
- Update the `title` in the frontmatter
- Move the file to the `dest_path` (or cwd)
We have all the information we need to help the user set up a
redirection, so ideally we would.  Unfortunately, that will require:
1. Deciding on an approach (alias vs file)
2. Refactoring the code necesary to make either work.
This has now been split out into #403.
Fixes #393

feat: `rename` subcommand

---

src/cobalt_model/config.rs
src/cobalt_model/mark.rs

Add an enabled option to the `syntax_highlight` category of `_cobalt.yml`. When set to `false`, cobalt will not perform syntax highlighting in Markdown files. The default is `true`, so this should be totally backwards compatible with the current functionality.
Do we also want to remove the compile time options for syntax-highlighting? If compiling with the feature adds extra dependencies, there are some potential benefits to keeping the compile time options in, however this could cause some confusion.
I'm not overly familiar with the architecture of this project, so feel free to let me know if there is a way you would rather me implement this or if there is some way to improve this PR.
Closes #343

feat: add runtime configuration to built in syntax highlighting

---

src/syntax_highlight/syntect.rs

to get rid of deprecation warning

fix(deprecation): remove `use std::ascii::AsciiExt` 

---

Cargo.lock

Because the `liquid-{compiler, interpreter, value}` crates were still pinned to `0.16.0`, the fix from cobalt-org/liquid-rust#207 , wasnt passed down to #527.

Update pinned liquid sub-crates

---

src/bin/cobalt/serve.rs

Makes it possible to open the site in a browser with Ctrl+click.

Add "http://" prefix to server address

---

src/cobalt_model/document.rs

#431 
Documents can optionally start with a `---` now.  The code I added essentially checks if the document has front matter surrounded by `---` and if so, it removes the first line and then the logic for separating the front matter stays the same. I added a couple tests as well.
Questions and suggestions are welcome and encouraged! I tried a few ideas before settling on this.

Document frontmatter can now be surrounded by ---

---

.travis.yml
Cargo.lock
src/error.rs

- Fix deeply nested array index (`a.b[0]`)
- Improve liquid error reporting
- Add `.first` and .last` variables
- Array manipulation filters
- Richer if conditions
- `tablerow`

feat: Upgrade liquid

---

Cargo.lock
Cargo.toml
src/cobalt_model/collection.rs
src/cobalt_model/config.rs
src/cobalt_model/site.rs
src/cobalt_model/template.rs
src/document.rs
src/lib.rs
src/pagination.rs
src/syntax_highlight/null.rs
src/syntax_highlight/syntect.rs
tests/mod.rs

Too many features, bug fixes, and performance gains to name.
See https://github.com/cobalt-org/liquid-rust/blob/master/CHANGELOG.md#0180-2018-12-27
BREAKING CHANGE: Besides any caused by the liquid upgrade, we no longer
support includes outside of the `_include` directory.

feat(liquid): Upgrade

---

src/cobalt_model/frontmatter.rs

Because "no tags" is `None` and "no preference" is `one`, we need to
allow `[]` to also represent `no tags` and convert it to `None`.
See #550

feat(tags): Allow overriding default tag

---

.travis.yml
Cargo.lock
Cargo.toml
src/bin/cobalt/new.rs
src/cobalt_model/collection.rs
src/cobalt_model/config.rs
src/cobalt_model/frontmatter.rs
src/cobalt_model/mod.rs

addresses https://github.com/cobalt-org/cobalt.rs/issues/562
still need to figure out flag's name and it behaviour (see RFC)

feat(add-date-prefix-on-publish): implementation

---

src/cobalt_model/files.rs

The underlaying structure's order is not fixed and may depend on
the filesystem implementation. Therefor the iterator needs to be
sorted by filename to guarantee a reproducible order of processing
input files.
One effect of this issue can be observed by having an unreproducible
order of posts that have the very same published_date (or none as
that falls back to default_date) purely depending on the order the
underlaying filesystem serves the files for consumption.
This fixes #457

fix(files): sort by filename to have a reproducibly walking iterator

---

src/cobalt_model/files.rs
src/cobalt_model/template.rs
src/syntax_highlight/syntect.rs

Added `dyn` where the compiler told me to do so to get rid of the warnings that appeared in Rust 1.37

chore: fix warnings on trait object without `dyn` keyword

---

src/document.rs

Setting `excerpt_separator` to the empty string is intended to disable
auto-extracted excerpts, and, as a side-effect, cause the full content
to be used in the RSS feed.
Before this change, this did not happen, as
`Document::description_to_str` would render the `Nil` value inserted
into the "excerpt" attribute in all cases.
Fixes #724.

fix: Do not render `Nil` excerpt

---

Cargo.toml
src/cobalt_model/frontmatter.rs
tests/mod.rs

With `master` being on life support while `next` is doing major work, we can live with any less-than-ideals of this API for now.

feat: Pagination is now stable-enough

---

src/bin/cobalt/serve.rs

Added content type to 404 respsonse so that the html is rendered as previously it was just handling it as raw text.

fix(serve): added content type to 404 response

---

Cargo.lock
Cargo.toml
src/cobalt.rs
src/cobalt_model/assets.rs
src/cobalt_model/config.rs
src/cobalt_model/mod.rs
src/cobalt_model/sass.rs
src/document.rs
tests/fixtures/example_minified/_cobalt.yml
tests/fixtures/example_minified/_layouts/default.liquid
tests/fixtures/example_minified/_layouts/posts.liquid
tests/fixtures/example_minified/index.liquid
tests/fixtures/example_minified/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/example_minified/static/example.css
tests/fixtures/example_minified/static/example.js
tests/mod.rs
tests/target/example_minified/index.html
tests/target/example_minified/posts/2014-08-24-my-first-blogpost.html
tests/target/example_minified/static/example.css
tests/target/example_minified/static/example.js

- Minifies rendered documents
- Minifies js, and css assets
Minification is disabled by default, for backward and text compatibility.  This can be changed on an extension-by-extension basis.
This doesn't touch the unused config crate.

feat: Minify html,css,js

---

src/cobalt.rs

The extra XML declaration prevents the XML from being parsed.

Remove duplicate XML declaration in RSS file.

---

Cargo.lock
crates/core/Cargo.toml
crates/core/src/lib.rs
crates/core/src/source.rs
src/bin/cobalt/args.rs
src/bin/cobalt/build.rs
src/bin/cobalt/debug.rs
src/bin/cobalt/new.rs
src/bin/cobalt/serve.rs
src/cobalt.rs
src/cobalt_model/assets.rs
src/cobalt_model/collection.rs
src/cobalt_model/config.rs
src/cobalt_model/files.rs
src/cobalt_model/frontmatter.rs
src/cobalt_model/mod.rs
src/cobalt_model/pagination.rs
src/cobalt_model/sass.rs
src/document.rs
src/lib.rs
src/pagination/categories.rs
src/pagination/dates.rs
src/pagination/paginator.rs
src/pagination/tags.rs

This doesn't just pull out file walking logic but switches us from
walking per type of file to walking once and categorizing as we go,
which simplifies our walking logic and is easier to integrate into
whatever processing system we adopt.
This also includes all of the refactors, additional tests, etc to prepare for this refactor.

refactor(core): Pull out file walking 

---

src/cobalt_model/site.rs

This is the same option that is present in jekyll (as a global variable).
I'm rewriting the areweinspaceyet.org with rust and I want to keep it.
In a nutshell, it shows when was the last time the website was generated (updated).
https://github.com/AeroRust/are-we-in-space-yet/blob/933b45db16c2585f68d2ce0c9a03640ad6604366/_includes/footer.html#L19

cobalt_model - Add a `time` to Site

---

Cargo.lock
Cargo.toml
src/bin/cobalt/serve.rs

Because we override the config to work better for serve, we shouldn't
override the users copy of the files which they might publish, thinking
they are prestine.
Fixes #834

fix(cli): Serve from temp dir

---

Cargo.lock
Cargo.toml
crates/file-serve/Cargo.toml
crates/file-serve/src/lib.rs
src/bin/cobalt/serve.rs

We'll now auto-discover a port to host from, rather than using a hard
coded default.

fix(serve): Avoid port conflicts

---

src/cobalt_model/config.rs
src/cobalt_model/mark.rs
src/cobalt_model/template.rs
src/cobalt_model/vwiki.rs
src/syntax_highlight.rs
tests/cli_tests.rs
tests/cmd/publish_draft.in/_cobalt.yml
tests/cmd/publish_post.in/_cobalt.yml
tests/cmd/publish_post_with_date.in/_cobalt.yml
tests/cmd/rename_page.in/_cobalt.yml
tests/fixtures/init/_cobalt.yml

My goal is to run more tests with `--no-default-features`.  When I tried
it, a lot of CLI tests failed because we were logging that the theme
wasn't supported. I decided to disable syntax highlighting to make my
life easier, but the warning persisted, uncovering this bug.

fix: Respect enabled with liquid syntax highlighting 

---

.github/workflows/ci.yml
.github/workflows/rust-next.yml
src/cobalt_model/template.rs

Instead of failing, we should ignore and move on.  Ideally, we'd do the
same as `EagerCompiler` and error on access but this is good enough for
now.
Fixes #1022

fix(build): Binary files stop build

---

src/bin/cobalt/debug.rs
src/cobalt.rs
src/cobalt_model/config.rs
src/cobalt_model/mark.rs
src/cobalt_model/template.rs
src/lib.rs
src/syntax_highlight.rs

This will make it easier for the config to have an impact on syntax highlighting rather.

refactor: Inject highlighting into markdown/liquid

---

Cargo.lock
Cargo.toml
src/bin/cobalt/serve.rs

We lost debouncing again.  The new API is more limited than I would like.
I think this will take care of #884

chore: Upgrade notify

---

src/document.rs
src/error.rs
tests/cmd/yaml_error.md

This PR is probably not really ready to merge, as it does not solve the more general problem. I'd like some feedback before I go further.
If you have a syntax error in the front matter of a post, the error message does not give you any hint which part might be wrong:
```
Building from `d:\src\awise.us\input` into `E:\externsrc\cobalt.rs\_site`
Error: Failed to parse posts/2005-10-24-starting-up.md
Info: caused by Failed to parse frontmatter
```
After the changes in this PR, a slightly more helpful error message is printed:
```
Building from `d:\src\awise.us\input` into `E:\externsrc\cobalt.rs\_site`
Error: Failed to parse posts/2005-10-24-starting-up.md
Info: caused by Failed to parse frontmatter
Info: caused by the 'offset minute' component could not be parsed
```
You can see me fixing …

Better error message when failing to parse front matter on post

---

crates/file-serve/README.md
crates/file-serve/src/lib.rs
src/bin/cobalt/serve.rs

Assume that someone was developing an App which would serve some files temporarily, the server should be closed when it was no longer needed. But the server was just blocked for handling incoming requests, there were no valid methods to close it.
So a method for graceful shutdown of the server is introduced in this PR, also a method for checking whether a sever is running.
BREAKING CHANGE: `Server.serve()` returns `Result<(), Error>` instead of `Result<Infallible, Error>` because the server can be closed.
Remove `Debug` trait of `Server`.

feat(file-serve)!: Allow graceful shutdown of server

---

src/bin/cobalt/serve.rs

Why? Tunneling! For example GitHub Codespaces will tunnel your port 1234 on your codespace's localhost to https://sometunnel-1234.githubcodespaces.example.org/. if you try to get `http://localhost:1234/style.css` then it fails since its not on localhost; its on a completely separate domain
ex:
```html
<link rel=stylesheet href="{{ site.base_url }}/style.css">
```
This pr (hopefully) would fix that by turning the HTML from this:
```html
<link rel=stylesheet href="http://localhost:1234/style.css">
```
into this which works across localhost and tunnels
```html
<link rel=stylesheet href="/style.css">
```

use / as base url instead of host addr in serve cmd

---

crates/engarde/src/raw.rs

fix: html escape bug with utf-8 characters

---

src/bin/cobalt/serve.rs

Hi,
In the last release `cobalt serve` fail if sitemap is enabled, this is because sitemap require a full url and so the required base_url should be full, the serve replace the base_url with a '/' which cause the problem, this just replace the "/" with the current addr of the server.

fix: cobalt serve work correctly with sitemap

---

.github/workflows/ci.yml
.gitignore

Fix the coverage CI job by allowing more time to run the tests under code coverage.
Also: add the `coverage `folder generated by tarpaulin to `.gitignore`

Coverage fixes

---

crates/engarde/src/syntax.rs
src/bin/cobalt/debug.rs
tests/cli_tests.rs
tests/cmd/syntax_highlighting.in/_layouts/default.liquid
tests/cmd/syntax_highlighting.in/_layouts/posts.liquid
tests/cmd/syntax_highlighting.in/index.liquid
tests/cmd/syntax_highlighting.in/posts/2022-08-23-my-first-post.md
tests/cmd/syntax_highlighting.md
tests/cmd/syntax_highlighting.out/_dest/index.html
tests/cmd/syntax_highlighting.out/_dest/posts/2022-08-23-my-first-post.html
tests/cmd/syntax_highlighting_css.in/_cobalt.yml
tests/cmd/syntax_highlighting_css.in/_layouts/default.liquid
tests/cmd/syntax_highlighting_css.in/_layouts/posts.liquid
tests/cmd/syntax_highlighting_css.in/index.liquid
tests/cmd/syntax_highlighting_css.in/posts/2022-08-23-my-first-post.md
tests/cmd/syntax_highlighting_css.md
tests/cmd/syntax_highlighting_css.out/_dest/index.html
tests/cmd/syntax_highlighting_css.out/_dest/posts/2022-08-23-my-first-post.html
tests/cmd/syntax_highlighting_disabled.in/_cobalt.yml
tests/cmd/syntax_highlighting_disabled.in/_layouts/default.liquid
tests/cmd/syntax_highlighting_disabled.in/_layouts/posts.liquid
tests/cmd/syntax_highlighting_disabled.in/index.liquid
tests/cmd/syntax_highlighting_disabled.in/posts/2022-08-23-my-first-post.md
tests/cmd/syntax_highlighting_disabled.md
tests/cmd/syntax_highlighting_disabled.out/_dest/index.html
tests/cmd/syntax_highlighting_disabled.out/_dest/posts/2022-08-23-my-first-post.html

This theme doesn't specify any color but uses the `ClassedHTMLGenerator` to generate CSS classes instead. This allow to have per-color-scheme themes and to easily edit themes manually.
This is similar to Zola [classed-highlighting](https://www.getzola.org/documentation/content/syntax-highlighting/#inline-vs-classed-highlighting) feature except with a `c-` prefix instead of a `z-` one.
It generates css classes like that (whitespace modified for readibility):
```html
<pre class="language-rust highlighter-syntect">
<code class="highlight"><span class="c-source c-rust">
<span class="c-support c-macro c-rust">println!</span>
<span class="c-meta c-group c-rust">
<span class="c-punctuation c-section c-group c-begin c-rust">(</span>
</span>
<span class="c-meta c-group c-rust">
<span …
```

feat: Add a 'css' theme for syntax highlighting
