cobalt-org/cobalt.rs

src/cobalt.rs
src/document.rs

Hey there, 
as I am new to the project, I scanned through most of the code to get acquainted to it. I did some slight changes while reading:
fixed compiler warnings, completly removed markdown (see https://github.com/cobalt-org/cobalt.rs/commit/3b005d9ae73b2ea8691e803d5a904abf87d29d9e) and slightly simplfied some lines
Feel free to not merge, ignore and close this PR if its not useful

Mini refactoring

---

README.md

See #19 and #16 I think it is better to avoid some confusion here.

Added note about Rust version (1.0 does not work)

---

Cargo.toml
src/cobalt.rs
src/document.rs
src/lib.rs

Uses crossbeam scoped threads to run document creation in parallel. This
can definitely be improved, as I still have to make some Arcs for things
and join guards to sync in the end, which should not be neccessary if I
understand crossbeam correctly. Well, it's a start.

Create documents in parallel

---

src/cobalt.rs
tests/fixtures/dotfiles/_layouts/default.tpl
tests/fixtures/dotfiles/_layouts/posts.tpl
tests/fixtures/dotfiles/_posts/2014-08-24-my-first-blogpost.md
tests/fixtures/dotfiles/index.tpl
tests/mod.rs
tests/target/dotfiles/_posts/2014-08-24-my-first-blogpost.html
tests/target/dotfiles/index.html

Don't try to read dotfiles in the layout directory. In my case these were vim swap files which don't contain valid UTF-8.
This PR is based on #32, not master, so I'll rebase after (if) that is merged.

Skip layout dotfiles

---

src/cobalt.rs
tests/fixtures/copy_files/_layouts/default.tpl
tests/fixtures/copy_files/_layouts/posts.tpl
tests/fixtures/copy_files/_posts/2014-08-24-my-first-blogpost.md
tests/fixtures/copy_files/index.liquid
tests/fixtures/copy_files/some.js
tests/fixtures/copy_files/style/blog.css
tests/mod.rs
tests/target/copy_files/_posts/2014-08-24-my-first-blogpost.html
tests/target/copy_files/index.html
tests/target/copy_files/some.js
tests/target/copy_files/style/blog.css

Small fix for copying nested folders. Resolves #59.

Fix for copy files bug

---

README.md

Just a smiple PR that adds some example websites. I couldn't remmeber the other ones that we discussed. Just let me know if there are any others.

added example websites to cobalt readme

---

src/document.rs

Example usage:
```
{% if is_post %}
{% include src/_layouts/post.liquid %}
{% else %}
{{ content }}
{% endif %}
```

Added is_post gobal to allow users to detect if they are a post or not

---

src/cobalt.rs
src/document.rs

file_system is now passed to liquid

---

src/document.rs

This is a temporary fix for #62.

Fix for Windows path issue

---

src/lib.rs
src/main.rs
src/new.rs

This command can be called via `cobalt new myBlog`. There are no tests because I could not find a way to write good tests for this type of thing. This should fix #67.

New command

---

README.md

I added few updates to the readme tell me how you guys like it. The rendered readme can be seen on my fork. https://github.com/LucioFranco/cobalt.rs

Add deployment and content list to README

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cobalt-org/cobalt.rs/116)

add my blog on cobalt.rs

---

Cargo.toml
src/main.rs

I propose this change because is easier to improve the command subcommands parameters using clap.

Migrate from getopt to clap

---

README.md
src/cobalt.rs
src/config.rs
src/document.rs
src/main.rs
tests/fixtures/drafts/.cobalt.yml
tests/fixtures/drafts/_drafts/a-draft-post.md
tests/fixtures/drafts/_layouts/default.liquid
tests/fixtures/drafts/_layouts/posts.liquid
tests/fixtures/drafts/index.liquid
tests/fixtures/drafts/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/drafts_not_shown_by_default/_drafts/a-draft-post.md
tests/fixtures/drafts_not_shown_by_default/_layouts/default.liquid
tests/fixtures/drafts_not_shown_by_default/_layouts/posts.liquid
tests/fixtures/drafts_not_shown_by_default/index.liquid
tests/fixtures/drafts_not_shown_by_default/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/drafts_not_shown_by_default/posts/this-is-a-draft.md
tests/mod.rs
tests/target/drafts/index.html
tests/target/drafts/posts/2014-08-24-my-first-blogpost.html
tests/target/drafts/posts/a-draft-post.html
tests/target/drafts_not_shown_by_default/index.html
tests/target/drafts_not_shown_by_default/posts/2014-08-24-my-first-blogpost.html

Clone from #124 because I made a new branch.
@LucioFranco ready to merge?

Draft support

---

src/main.rs

This should fix the issue in #129

fix for --silent and --trace not enabling its log level

---

.gitignore
Cargo.toml
tests/mod.rs

Suggested by @johannhof, closes #65

Use tempdir crate instead of home-grown tests/tmp

---

src/cobalt.rs

Strip all non-`Path` things from `build()`.
Exceptions: `OsStr` for *dirwalk*.

Path only in build()

---

Cargo.lock
Cargo.toml
README.md
src/document.rs
src/lib.rs
src/main.rs
src/syntax_highlight.rs
tests/cli.rs
tests/fixtures/syntax_highlight/rust.md
tests/mod.rs
tests/target/syntax_highlight/rust.html

Add warning message if the current directory is being deleted.

---

build.sh
src/cobalt.rs
src/syntax_highlight.rs
tests/fixtures/posts_in_subfolder/.cobalt.yml
tests/fixtures/posts_in_subfolder/README.md
tests/fixtures/posts_in_subfolder/_layouts/default.liquid
tests/fixtures/posts_in_subfolder/_layouts/post.liquid
tests/fixtures/posts_in_subfolder/index.liquid
tests/fixtures/posts_in_subfolder/posts/2017/01/05/post.md
tests/fixtures/posts_in_subfolder/posts/2017/01/08/post.md
tests/fixtures/posts_in_subfolder/posts/20170103/post.md
tests/fixtures/posts_in_subfolder/posts/post.md
tests/mod.rs
tests/target/posts_in_subfolder/README.html
tests/target/posts_in_subfolder/index.html
tests/target/posts_in_subfolder/posts/2017/01/05/post.html
tests/target/posts_in_subfolder/posts/2017/01/08/post.html
tests/target/posts_in_subfolder/posts/20170103/post.html
tests/target/posts_in_subfolder/posts/post.html

This superseds pull request https://github.com/cobalt-org/cobalt.rs/pull/134 because I have completely started over the test.
After applying, pull request 134 can be dropped.
Additional Infos:
1. cargo fmt also changes src/main.rs I have not touched
2. did not run clippy, because it doesn't compile at the moment

Posts in subdirs

---

src/cobalt.rs

This fixes #190 and #183
I'm not sure how to write a test  for that. If anybody has an idea just let me know :smile:

Fix wrong relative path generation

---

src/cobalt.rs
tests/fixtures/previous_next/_layouts/default.liquid
tests/fixtures/previous_next/_layouts/posts.liquid
tests/fixtures/previous_next/index.liquid
tests/fixtures/previous_next/posts/2014-08-24-my-first-blogpost.md
tests/fixtures/previous_next/posts/2014-08-25-my-second-blogpost.md
tests/fixtures/previous_next/posts/2014-08-26-my-third-blogpost.md
tests/mod.rs
tests/target/previous_next/index.html
tests/target/previous_next/posts/2014-08-24-my-first-blogpost.html
tests/target/previous_next/posts/2014-08-25-my-second-blogpost.html
tests/target/previous_next/posts/2014-08-26-my-third-blogpost.html

Fix for #139. Based on [this PR](https://github.com/cobalt-org/cobalt.rs/pull/163) but with just the changes to the post attributes.

Add previous and next attributes to posts

---

Cargo.lock
Cargo.toml
src/cobalt.rs
src/config.rs
src/error.rs
src/files.rs
src/lib.rs
src/main.rs
tests/cli.rs
tests/mod.rs

The `ignore` field in `.cobalt.yml` is changing from a list of glob patterns to
a list `gitignore` patterns, allowing whitelisting and more advanced
whitelisting/blacklisting with well defined semantics.
Previuously, Cobalt processed all files except `.dot` and `_hidden`,
*dest* files/directories.
Considerations when designing this:
- User workflow: users need `.dot` asset files, like `.htaccess`, copied over.
- Implementation: Finding files for pages and posts is coupled together
which will be a problem as we refactor them into more general
collections or sections.
- Performance: Eventually we'll want to implement incremental rebuild
(see issue #81) and to do so we'll need to know what collection a file
notification is relevant to.
`gitignore` patterns were selected for the first item to …

feat: Increase control over files to process 

---

README.md

add sda.io

---

Cargo.lock
Cargo.toml
src/cobalt.rs
src/config.rs
src/error.rs
src/lib.rs
src/main.rs

This is useful for
- Seeing what variables are available
- Isolate bugs to be either in cobalt or liquid

feat(debug): Dump intermediate state

---

src/files.rs

- Improved the behavior of the immediate calls compared to the walking behavior
- Added tests for whitelisting

Continuation of #227

---

README.md

Hi,
my site is now also switched to Cobalt :)

Add site uwe-arzt.de to README.md

---

.travis.yml
appveyor.yml
src/syntax_highlight/syntect.rs

This attempts to address some recent problems
- liquid drew attention to `!` being swallowed, so using real `if`s
- Compiling rustfmt adds 5 minutes to the build
- Saw some problems with the cmake ppa.

Improve CI process

---

tests/cli.rs

And some test clean up.
I don't quite remember what my goal was.

tests: Test cobalt init

---

src/bin/cobalt/main.rs
src/cobalt.rs
src/files.rs
src/lib.rs

This should improve things though I suspect it breaks some other cases.
I'm hoping some future changes like #284 and refactors I have in mind will help to make this handle all cases.

Fix watch/build having problems with `dest`

---

.gitignore
src/bin/cobalt/main.rs
src/jekyll/jk_document.rs
src/jekyll/jk_errors.rs
src/jekyll/mod.rs
src/lib.rs

Had to delete my fork and start again. I don't know how to work with git and forks

Third take to convert jekyll's posts to cobalt

---

.travis.yml
src/bin/cobalt/main.rs
src/bin/cobalt/serve.rs
src/cobalt.rs
src/jekyll/jk_document.rs
src/legacy/wildwest.rs
src/lib.rs

Also
- Improve tool caching
- Run rustfmt, clippy in separate jobs for parallelism

Re-enable clippy

---

src/document.rs
tests/fixtures/markdown_table/_layouts/default.liquid
tests/fixtures/markdown_table/index.md
tests/mod.rs
tests/target/markdown_table/index.html

fix(md): Add table/ref support

---

src/config.rs

fix(config): Don't support absolute paths

---

src/cobalt.rs
src/config.rs
src/legacy/wildwest.rs

This finishes off the consistency work

fix(config): Posts name is now title

---

src/bin/cobalt/args.rs
src/cobalt.rs
src/config.rs
src/document.rs
src/legacy/wildwest.rs
src/sass.rs
src/site.rs
src/template.rs

This fixes a lot of bugs that become more obvious with the migration.

Prep for migration to new formats

---

src/bin/cobalt/main.rs
src/bin/cobalt/serve.rs

- Merge `watch` and `serve`
- Don't exit on a rebuild error
- Auto-adjust `site.base_url`

Improve usefulness of `cobalt serve`

---

Cargo.lock
Cargo.toml
src/cobalt_model/slug.rs
src/lib.rs

fix(slug): Dont ignore non-ascii in slug

---

.gitignore
.travis.yml
Cargo.toml
appveyor.yml

Trying by keeping VS2017 and bump Rust stable version

feat(sass): Enable by default

---

src/cobalt_model/mod.rs
src/cobalt_model/permalink.rs
src/document.rs

refactor(permalink): extract permalink parsing into its own module

---

Cargo.lock
Cargo.toml
src/lib.rs
src/syntax_highlight/syntect.rs
tests/target/syntax_highlight/rust.html
tests/target/syntax_highlight_theme/rust.html

I ran `ldd` on cobalt to ensure static linking was still happening.

chore: Upgrade syntect

---

.travis.yml
Cargo.lock
Cargo.toml
src/bin/cobalt/args.rs
src/bin/cobalt/build.rs
src/bin/cobalt/debug.rs
src/bin/cobalt/new.rs
src/bin/cobalt/serve.rs
src/cobalt.rs
src/cobalt_model/collection.rs
src/cobalt_model/config.rs
src/cobalt_model/frontmatter.rs
src/cobalt_model/permalink.rs
src/cobalt_model/site.rs
src/document.rs
src/lib.rs
src/syntax_highlight/null.rs
src/syntax_highlight/syntect.rs

See https://github.com/cobalt-org/liquid-rust/issues/201
There might also be performance improvements from the upgraded liquid.

feat: Liquid for-block works on hashes

---

Cargo.lock

See https://github.com/cobalt-org/liquid-rust/issues/207

feat(liquid): filter input can index

---

Cargo.toml
src/cobalt_model/frontmatter.rs
src/cobalt_model/mod.rs
src/cobalt_model/pagination_config.rs

Here is the frontmatter part of the pagination feature :)
I'm kinda slow because new game but I'm still in to complete this feature!
You wanted to put a feature flag on this to avoid disruption on the master branch, but I don't know where to put it :-/
`PaginationConfigBuilder::build`?

feat(pagination): pagination frontmatter

---

Cargo.lock
src/bin/cobalt/main.rs

The goal is smaller binary and easier memory profiling.

 perf: Switch to system allocator

---

Cargo.lock
Cargo.toml
src/document.rs

Breaking Changes
* **for_block:**  make ranges inclusive. ([42055c35](https://github.com/cobalt-org/liquid-rust/commit/42055c356125b0e66524a5ee7a2fa34e4af4397c))
Features
* Indexing by variable ([c216a439](https://github.com/cobalt-org/liquid-rust/commit/c216a439d978bedb88ec4baba0e8703d6877e20e), closes [#209](https://github.com/cobalt-org/liquid-rust/issues/209))
* **for_block:**  support parameters with variables ([7376ccf5](https://github.com/cobalt-org/liquid-rust/commit/7376ccf51f5d2f0a67ca0dbad3d25d395f4fbd6d), closes [#162](https://github.com/cobalt-org/liquid-rust/issues/162))
* **filters:**
* Added: "at_most" ([be3e55c0](https://github.com/cobalt-org/liquid-rust/commit/be3e55c079fe43f8f35ebe5add00fd05ef912f79))
* Added: "at_least" …

feat(liquid): Update to 0.17

---

src/cobalt_model/frontmatter.rs
src/document.rs

Resolves https://github.com/cobalt-org/cobalt.rs/issues/550

feat(tags-first-citizen): support `tags` in frontmatter's root

---

src/bin/cobalt/new.rs

fix for https://github.com/cobalt-org/cobalt.rs/issues/562#issuecomment-453863642
sorry for the lack of concentration on this one :(

fix(publish): collection detection was failing

---

src/cobalt_model/pagination_config.rs
src/pagination.rs
tests/fixtures/pagination_categories/_layouts/default.liquid
tests/fixtures/pagination_categories/_layouts/posts.liquid
tests/fixtures/pagination_categories/index.liquid
tests/fixtures/pagination_categories/posts/my-first-blogpost.md
tests/fixtures/pagination_categories/posts/my-fith-blogpost.md
tests/fixtures/pagination_categories/posts/my-fourth-blogpost.md
tests/fixtures/pagination_categories/posts/my-second-blogpost.md
tests/fixtures/pagination_categories/posts/my-third-blogpost.md
tests/mod.rs
tests/target/pagination_categories/categories/cat1/cat2/index.html
tests/target/pagination_categories/categories/cat1/index.html
tests/target/pagination_categories/categories/cata/catb/index.html
tests/target/pagination_categories/categories/cata/index.html
tests/target/pagination_categories/index.html
tests/target/pagination_categories/posts/my-first-blogpost.html
tests/target/pagination_categories/posts/my-fith-blogpost.html
tests/target/pagination_categories/posts/my-fourth-blogpost.html
tests/target/pagination_categories/posts/my-second-blogpost.html
tests/target/pagination_categories/posts/my-third-blogpost.html

More pagination!
related RFC: https://github.com/cobalt-org/cobalt.rs/issues/395

feat(pagination): indexation by categories

---

contrib/cobalt-git-deploy

I hope scripts like these are in the scope of the `cobalt.rs` repository. I have an accompanying PR for the cobalt website in preparation, but I first need to know whether this PR is acceptable, so I can reference the script from the website PR.

Add script for deploying from a git `post-update` hook

---

src/cobalt_model/files.rs

Micro PR to solve a deprecation warning

fix(deprecation): replace trim_left_matches by trim_start_matches

---

src/cobalt_model/frontmatter.rs
src/cobalt_model/pagination_config.rs
src/document.rs
tests/fixtures/pagination_sort_by_weight/_layouts/default.liquid
tests/fixtures/pagination_sort_by_weight/_layouts/posts.liquid
tests/fixtures/pagination_sort_by_weight/index.liquid
tests/fixtures/pagination_sort_by_weight/posts/my-first-blogpost.md
tests/fixtures/pagination_sort_by_weight/posts/my-fith-blogpost.md
tests/fixtures/pagination_sort_by_weight/posts/my-fourth-blogpost.md
tests/fixtures/pagination_sort_by_weight/posts/my-second-blogpost.md
tests/fixtures/pagination_sort_by_weight/posts/my-third-blogpost.md
tests/mod.rs
tests/target/pagination_sort_by_weight/index.html
tests/target/pagination_sort_by_weight/posts/my-first-blogpost.html
tests/target/pagination_sort_by_weight/posts/my-fith-blogpost.html
tests/target/pagination_sort_by_weight/posts/my-fourth-blogpost.html
tests/target/pagination_sort_by_weight/posts/my-second-blogpost.html
tests/target/pagination_sort_by_weight/posts/my-third-blogpost.html

added `weight` field in frontmatter in order to tackle https://github.com/cobalt-org/cobalt.rs/issues/671

feat(pagination): sort by weight

---

Cargo.lock
Cargo.toml
src/cobalt_model/template.rs
src/syntax_highlight/null.rs
src/syntax_highlight/syntect.rs

fix(liquid): Upgrade to 0.19

---

Cargo.lock
Cargo.toml
src/cobalt.rs
src/cobalt_model/config.rs
src/document.rs
tests/fixtures/sitemap/_cobalt.yml
tests/fixtures/sitemap/_layouts/default.liquid
tests/fixtures/sitemap/_layouts/posts.liquid
tests/fixtures/sitemap/index.liquid
tests/fixtures/sitemap/other_page.liquid
tests/fixtures/sitemap/posts/my-fifth-blogpost.md
tests/fixtures/sitemap/posts/my-first-blogpost.md
tests/fixtures/sitemap/posts/my-fourth-blogpost.md
tests/fixtures/sitemap/posts/my-second-blogpost.md
tests/fixtures/sitemap/posts/my-third-blogpost.md
tests/mod.rs
tests/target/sitemap/index.html
tests/target/sitemap/other_page.html
tests/target/sitemap/posts/my-fifth-blogpost.html
tests/target/sitemap/posts/my-first-blogpost.html
tests/target/sitemap/posts/my-fourth-blogpost.html
tests/target/sitemap/posts/my-second-blogpost.html
tests/target/sitemap/posts/my-third-blogpost.html
tests/target/sitemap/sitemap.xml

This implement the sitemap support with the use of sitemap crate, as wrote in this issue: https://github.com/cobalt-org/cobalt.rs/issues/452

add support for sitemap generation

---

Cargo.lock
Cargo.toml
src/bin/cobalt/serve.rs

This also slips in a fix for when the user does not have a 404 file and cleans up some code, whoops.

chore: Upgrade actix

---

azure-pipelines.yml
src/bin/cobalt/args.rs
src/bin/cobalt/build.rs
src/bin/cobalt/new.rs
src/cobalt.rs
src/cobalt_model/config.rs
src/cobalt_model/datetime.rs
src/cobalt_model/files.rs
src/cobalt_model/frontmatter.rs
src/cobalt_model/pagination_config.rs
src/document.rs
src/pagination/dates.rs
tests/mod.rs

Fixes: #726
----
Note that while the code is now warning-free with current beta clippy,
the CI is not switched to beta -- that is left as an exercise to the
reader, if deemed desirable,

Get the code clippy-clean

---

Cargo.lock
Cargo.toml
src/bin/cobalt/serve.rs

fix(serve): Provide Content-Type 

---

Cargo.lock
Cargo.toml
src/bin/cobalt/serve.rs

added option to open in browser

feat(serve): Support for open in browser

---

Cargo.lock

fix(new): Use a valid published_date

---

src/bin/cobalt/serve.rs

Before this change, the serve command would repeatedly rebuild the website after the first change. This was caused by the the rebuild being triggered when the output files changed. The reason the existing check did not notice that the change files were in the output folder is due to how Rust canonicalizes paths on Windows.
Most Windows are familiar with absolute paths that start with the drive letter. For example:
```
c:\windows\notepad.exe
```
The fully qualified version of this path, returned by `canonicalize()`, is:
```
\\?\c:\windows\notepad.exe
```
The destination path was not canonicalized, while the paths coming from notify.rs were. This prevented the starts_with check from detecting that the changed path was within the destination folder.
I also tested this change on Linux and …

Fix infinite loop in serve command on Windows

---

src/cobalt_model/mark.rs

feat(md): Strike through and task lists

---

src/cobalt_model/frontmatter.rs
src/document.rs

This is part of our future work for pushing templating to be opt-in, for
performance.

feat(front): Allow disabling templating

---

src/document.rs

perf: Don't double-minify

---

Cargo.lock
Cargo.toml
crates/config/src/config.rs
crates/config/src/frontmatter.rs
src/cobalt.rs
src/cobalt_model/config.rs
src/cobalt_model/frontmatter.rs
src/cobalt_model/mod.rs
src/cobalt_model/vwiki.rs
src/document.rs
tests/fixtures/vimwiki_not_templated/_cobalt.yml
tests/fixtures/vimwiki_not_templated/_layouts/default.liquid
tests/fixtures/vimwiki_not_templated/index.wiki
tests/fixtures/vimwiki_not_templated_no_syntax/_cobalt.yml
tests/fixtures/vimwiki_not_templated_no_syntax/_layouts/default.liquid
tests/fixtures/vimwiki_not_templated_no_syntax/index.wiki
tests/mod.rs
tests/target/vimwiki_not_templated/index.html
tests/target/vimwiki_not_templated_no_syntax/index.html

Add vimwiki support to cobalt

---

Cargo.lock
Cargo.toml
crates/core/src/fs.rs
src/bin/cobalt/new.rs

feat(cli): cobalt new --edit support

---

crates/file-serve/src/main.rs
src/bin/cobalt/args.rs
src/bin/cobalt/build.rs
src/bin/cobalt/new.rs

fix: Error, rather than panic, on invalid CWD

---

crates/engarde/src/syntax.rs
src/syntax_highlight.rs
tests/cmd/custom_syntax_highlighting.out/_dest/posts/2022-08-23-my-first-custom-syntax.html

fix: wrap styled code blocks with <code> tags

---

src/document.rs

fix(jsonfeed): Populate with tags, if present

---

src/bin/cobalt/args.rs

fix(bin): Specify correct destination default

---

src/bin/cobalt/args.rs
src/bin/cobalt/build.rs

fix(serve): Don't offer unused `--destination`

---

src/pagination/categories.rs
tests/cmd/pagination_categories.out/_dest/categories.html
tests/cmd/pagination_categories.out/_dest/categories/cat1/index.html
tests/cmd/pagination_categories.out/_dest/categories/cata/index.html

fix(paging): Put pages under the correct category 

---

src/cobalt_model/frontmatter.rs
src/document.rs

fix: Always include page.tags

---

src/pagination/all.rs
src/pagination/categories.rs
src/pagination/dates.rs
src/pagination/mod.rs
src/pagination/tags.rs

The goal is to make it easier to jump into and compare the different paginators.

refactor(page): Clean up some pagiantor code

---

src/pagination/all.rs
src/pagination/tags.rs
tests/cmd/pagination_all_empty.in/_cobalt.yml
tests/cmd/pagination_all_empty.in/_dest/index.html
tests/cmd/pagination_all_empty.in/_layouts/default.liquid
tests/cmd/pagination_all_empty.in/_layouts/posts.liquid
tests/cmd/pagination_all_empty.in/index.liquid
tests/cmd/pagination_all_empty.md
tests/cmd/pagination_categories_empty.in/_cobalt.yml
tests/cmd/pagination_categories_empty.in/_dest/categories.html
tests/cmd/pagination_categories_empty.in/_layouts/default.liquid
tests/cmd/pagination_categories_empty.in/_layouts/posts.liquid
tests/cmd/pagination_categories_empty.in/index.liquid
tests/cmd/pagination_categories_empty.md
tests/cmd/pagination_dates_empty.in/_cobalt.yml
tests/cmd/pagination_dates_empty.in/_dest/dates.html
tests/cmd/pagination_dates_empty.in/_layouts/default.liquid
tests/cmd/pagination_dates_empty.in/_layouts/posts.liquid
tests/cmd/pagination_dates_empty.in/index.liquid
tests/cmd/pagination_dates_empty.md
tests/cmd/pagination_tags_empty.in/_cobalt.yml
tests/cmd/pagination_tags_empty.in/_dest/tags/index.html
tests/cmd/pagination_tags_empty.in/_layouts/default.liquid
tests/cmd/pagination_tags_empty.in/_layouts/posts.liquid
tests/cmd/pagination_tags_empty.in/index.liquid
tests/cmd/pagination_tags_empty.md

fix(page): Don't panic on empty all 
